name: go-fiber-clean-architecture

services:
  fiber:
    container_name: fiber-clean
    extends:
      file: compose.base.yml
      service: fiber
    ports:
      - ${FIBER_PORT}:${FIBER_PORT:-3100}

  db:
    extends:
      file: compose.base.yml
      service: db
    ports:
      - 5432:5432

  redis:
    extends:
      file: compose.base.yml
      service: redis
    ports:
      - 6379:6379
