services:
  fiber:
    container_name: fiber
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FIBER_PORT: ${FIBER_PORT}
      POSTGRES_NAME: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./:/app
    stdin_open: true
    tty: true

  db:
    image: postgres:16.2
    environment:
      POSTGRES_NAME: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/postgres/:/var/lib/postgresql/data

  redis:
    image: redis:7.2.5
    volumes:
      - ./redis-conf/:/usr/local/etc/redis/
      - ./db/redis/data:/var/lib/redis
    command: ['redis-server', '--include /usr/local/etc/redis/redis.conf']
